=== DemeoModdingGroup/mod-repository/schema/versions-v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://repo.demeomods.app/schema/versions-v1.json",
  "title": "Demeo Mods Versions v1 Schema",
  "type": "object",
  "$defs": {
    "version_object": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "min": {
              "type": "string"
            },
            "max": {
              "type": "string"
            }
          }
        }
      ]
    },
    "dependency_object": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "$ref": "#/$defs/version_object"
        },
        "reason": {
          "type": "string"
        }
      }
    }
  },
  "properties": {
    "schema_version": {
      "title": "The schema_version field",
      "type": "integer",
      "default": 1,
      "const": 1
    },
    "schema_type": {
      "title": "The schema_type field",
      "type": "string",
      "enum": ["project", "versions"],
      "default": "versions",
      "const": "versions"
    },
    "latest": {
      "title": "The latest field",
      "type": "string"
    },
    "latest_stable": {
      "title": "The latest field",
      "type": "string"
    },
    "versions": {
      "title": "The versions field",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "loader": {
            "type": "string",
            "enum": [
              "built-in",
              "MelonLoader",
              "BepInEx"
            ]
          },
          "changelog": {
            "type": "string"
          },
          "stable": {
            "type": "boolean"
          },
          "release_date": {
            "type": "string",
            "format": "date-time"
          },
          "demeo": {
            "$ref": "#/$defs/version_object"
          },
          "depends": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/dependency_object"
            }
          },
          "breaks": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/dependency_object"
            }
          },
          "file": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string",
                "format": "uri"
              },
              "sha256": {
                "type": "string"
              }
            },
            "required": ["name", "url", "sha256"]
          }
        },
        "required": [
          "name",
          "loader",
          "demeo",
          "file"
        ]
      }
    }
  },
  "required": [
    "schema_version",
    "schema_type",
    "latest",
    "latest_stable",
    "versions"
  ]
}

=== DemeoModdingGroup/mod-repository/projects/Py.LibLocalization/versions.json
{
    "schema_version": 1,
    "schema_type": "versions",
    "latest": "1.1.0",
    "latest_stable": "1.1.0",
    "versions": [
        {
            "name": "1.1.0",
            "loader": "built-in",
            "release_date": "2023-11-10T22:03:02Z",
            "stable": true,
            "changelog": "* Fix: Fixed an issue with HarmonyLoader using the wrong directory when looking for 0Harmony.dll\n* Refactor: Moved classes that don't need to be used by mod using the library to the `Py.LibLocalization.Internal` namespace.",
            "demeo": {
                "min": "1.32"
            },
            "file": {
                "name": "Py.LibLocalization-v1.1.0.zip",
                "url": "https://github.com/JustPyrrha/Py.LibLocalization/releases/download/v1.1.0/Py.LibLocalization-v1.1.0.zip",
                "sha256": "6d6e125b9bb8ceb74c8a97fbd015b9867dfc8f7437a130b099b8288ed2e45356"
            }
        },
        {
            "name": "1.0.0",
            "loader": "built-in",
            "release_date": "2023-10-26T02:51:16Z",
            "stable": true,
            "demeo": {
                "min": "1.32"
            },
            "file": {
                "name": "Py.LibLocalization-v1.0.0.zip",
                "url": "https://github.com/JustPyrrha/Py.LibLocalization/releases/download/v1.0.0/Py.LibLocalization-v1.0.0.zip",
                "sha256": "2fb9b629c724409a56f95c0a6221a222ed2a2f4b3ca9c985c2e1c84a85ee0d42"
            }
        }
    ]
}

=== DemeoModdingGroup/mod-repository/projects/Py.LibNetwork/versions.json
{
    "schema_version": 1,
    "schema_type": "versions",
    "latest": "1.0.0",
    "latest_stable": "1.0.0",
    "versions": [
        {
            "name": "1.0.0",
            "loader": "built-in",
            "release_date": "2023-10-29T07:37:15Z",
            "stable": true,
            "demeo": {
                "min": "1.32"
            },
            "file": {
                "name": "Py.LibNetwork-v1.0.0.zip",
                "url": "https://github.com/JustPyrrha/Py.LibNetwork/releases/download/v1.0.0/Py.LibNetwork-v1.0.0.zip",
                "sha256": "8cd38924cab8c38797bcf667fe59b862078eabd75924ae9342a9464080209a97"
            }
        }
    ]
}
